#!/bin/sh

# Function to send notifications using dunst
notify() {
    notify-send -u "$1" -t "$4" "$2" "$3" # Usage: notify <urgency> <title> <message> <time>
}

wallpaper=$(ls ~/Pictures/Wallpapers | dmenu -i -l 50 -g 1)

if [ $wallpaper -z ]; then
	notify "normal" "Wallpaper" "No wallpaper selected." 1500
else
	feh --bg-fill /home/krishna/Pictures/Wallpapers/$wallpaper
	notify "normal" "Wallpaper" "Wallpaper successfully changed to $wallpaper." 1000
fi
